### ISSUE TITLE
Add description to the project

### ISSUE THREAD

**Issue by crivotz** [zdharma-continuum/zinit-vim-syntax#1]
Can you add the description to the project?
This is the one from the old project:

`A Vim syntax definition for Zinit commands in any ft=zsh file`

it's a stupid thing but I have a script that keeps updated the list of [my vim/neovim configuration](https://github.com/crivotz/nv-ide) taking the project description.

Thanks

**Comment by pschmitt** [comment]
Thank you! Done!

Feel free open issues on the other description-less repos :)
